/*
-- Query: SELECT * FROM stayfit.exercises
LIMIT 0, 1000

-- Date: 2018-03-29 19:26
*/
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (1,1,'Standing Dumbbell Curl','In a biceps-focused list like this, you can’t leave out the classic curl. So we didn’t. (Don’t worry: The exercises will get more interesting.) But we would ask that you use a weight that makes sense: If you’re swaying back wildly and contorting your body—especially excessively arching your lower back—to lift the load, you should probably get a lighter pair of dumbbells.','standing_dumbbell_curl.jpg',1,0,0,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (2,3,'Deadlift','Arguably the king of all exercises, the deadlift hits every major muscle group hard, and is perhaps the greatest test of strength there is. Because of all the muscles involved, it releases a huge amount of testosterone (a muscle-building hormone) into the bloodstream. For this reason, the deadlift is a great cornerstone for any fitness plan.','deadlift.jpg',2,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (3,3,'Back Squat','Just like the deadlift, the barbell back squat hits just about every major muscle group there is in the body and is the king of leg-developing movements. Any athlete will tout the squat as the reason they run fast, jump high, and keep increasing in strength all over. ','back_squat.jpg',3,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (4,2,'Bench Press','Every gym-goer in the world has been asked “Whaddya bench?” at least once. This move is responsible for developing powerful, well-defined pecs, shoulders, and triceps, which lead to a more commanding presence, with or without a shirt on. Combine that with the muscle-building effects of the testosterone this move releases and all you have left to do is watch your “little black book” fill up.','bench_press.jpg',5,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (5,2,'Pullup','Nothing quite says “I’m big” like a wide set of shoulders; a wide back doesn\'t hurt either. The best move for developing those big, fan-shaped muscles (latissimus dorsi, aka, the lats) that make your shoulders look wide is the traditional pullup. It’s a big, multijoint move, which leads to testosterone release, meaning strength and overall muscle development will be enhanced.','pullup.jpg',2,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (6,2,'Barbell Overhead Press','Some would argue that the standing barbell overhead press is a better upper-body developer than the mighty bench press itself. Because it demands huge effort from your abs and all the assistance muscles that get used to press the barbell overhead; this move leads to a set of shoulders that look like cannonballs and will develop the chest just as well as any other move.','barbell_overhead_press.jpg',6,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (7,2,'Hack Squat','no description yet','hack_squat.jpg',3,0,0,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (8,2,'Dumbbel Incline Press','no description yet','dumbbel_incline_press.jpg',5,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (9,3,'T-Bar Row','no description yet','t_bar_row.jpg',2,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (10,2,'Incline Dumbbell Curl','no description yet','incline_dumbbell_curl.jpg',7,0,0,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (11,1,'Squats','no description yet','squats.jpg',3,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (12,1,'Push-Ups','no description yet','push_ups.jpg',5,0,1,0);
INSERT INTO `exercises` (`id`,`Difficulty`,`Name`,`Description`,`Image`,`MuscleGroup`,`Rating`,`IsBase`,`Voted`) VALUES (13,1,'Running','no description yet','running.jpg',8,0,1,0);
