-- MySQL Script generated by MySQL Workbench
-- Fri Mar 23 17:53:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema StayFit
-- -----------------------------------------------------
-- StayFit server application database

-- -----------------------------------------------------
-- Schema StayFit
--
-- StayFit server application database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `StayFit` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `StayFit` ;

-- -----------------------------------------------------
-- Table `StayFit`.`muscle_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`muscle_groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` TEXT(1024) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`exercises` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Difficulty` TINYINT(1) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(2000) NOT NULL,
  `Image` VARCHAR(1024) NOT NULL,
  `MuscleGroup` INT UNSIGNED NOT NULL,
  `Rating` TINYINT(2) NOT NULL,
  `IsBase` TINYINT NOT NULL DEFAULT 0,
  `Voted` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  INDEX `ActiveMusculeGroup_idx` (`MuscleGroup` ASC),
  CONSTRAINT `ActiveMusculeGroup`
    FOREIGN KEY (`MuscleGroup`)
    REFERENCES `StayFit`.`muscle_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`programs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`programs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1024) NOT NULL,
  `Image` VARCHAR(1024) NOT NULL,
  `Difficulty` TINYINT(1) NOT NULL,
  `Price` INT NOT NULL,
  `Rating` TINYINT(2) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Voted` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`browser_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`browser_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(1024) NOT NULL,
  `ItemType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`browser_category_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`browser_category_items` (
  `Category` INT UNSIGNED NOT NULL,
  `Item` INT UNSIGNED NOT NULL,
  CONSTRAINT `Category`
    FOREIGN KEY (`Category`)
    REFERENCES `StayFit`.`browser_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`muscles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`muscles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `LatinName` VARCHAR(200) NOT NULL,
  `Category` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `LatinName_UNIQUE` (`LatinName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `StayFit`.`exercise_muscles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `StayFit`.`exercise_muscles` (
  `Exercise` INT UNSIGNED NOT NULL,
  `Muscle` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Exercise`),
  INDEX `Muscle_idx` (`Muscle` ASC),
  CONSTRAINT `Exercise`
    FOREIGN KEY (`Exercise`)
    REFERENCES `StayFit`.`exercises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Muscle`
    FOREIGN KEY (`Muscle`)
    REFERENCES `StayFit`.`muscles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
